on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.1und1.de
          server_port: 465
          username: noreply@claimx.com
          password: ${{ secrets.NOREPLY_SMTP_PASSWORD }}
          subject: "Neues GitHub Issue: ${{ github.event.issue.title }}"
          to: techsupport@claimx.com
          from: noreply@claimx.com
          body: |
            Repository: ${{ github.repository }}

            Titel:
            ${{ github.event.issue.title }}

            Erstellt von:
            ${{ github.event.issue.user.login }}

            Link:
            ${{ github.event.issue.html_url }}

            Beschreibung:
            ${{ github.event.issue.body }}
