name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    type: [ "opened", "reopened", "synchronize" ]
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: P0sTGrE5*Pa55W0rt!
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        config:
        # [Python version, tox env]
        - ["3.7",   "py37"]
        - ["3.8",   "py38"]
        - ["3.9",   "py39"]
        - ["3.10",  "py310"]
        - ["3.11",  "py311"]

    runs-on: ubuntu-20.04
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config[0] }}
    - name: Setup PostgreSQL environment
      run: |
        echo "0.0.0.0:5432:*:postgres:P0sTGrE5*Pa55W0rt!" >> ~/.pgpass
        chmod 600 ~/.pgpass
    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.*', 'requirements.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Test
      env:
        POSTGRES_HOST: 0.0.0.0
        POSTGRES_USER: postgres
      run: ./pytest
    - name: Upload coverage RAW data
      if: ${{ matrix.config[0] == '3.9' }}
      uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: ".coverage*"
    - name: Upload Test Results
      if: ${{ matrix.config[0] == '3.9' }}
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: pytest.xml

  coverage:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/coverage.yml@master
    with:
      min_coverage: 95

  pre-commit:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pre_commit.yml@master

  sonarqube:
    needs: coverage
    uses: risclog-solution/gha_workflow_templates/.github/workflows/sonarqube.yml@master
    secrets:
      SONARQUBETOKEN: ${{ secrets.SONARQUBETOKEN }}

  publish-test-results:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/publish_test_results.yml@master
