name: Test

on:
  push:
    branches:
      - master
      - testing
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  test:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pytest_appenv.yml@master
    with:
      versions: >-
        ["3.8",]

  coverage:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/coverage.yml@master
    with:
      min_coverage: 80

  pre-commit:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pre_commit.yml@master

  sonarqube:
    needs: coverage
    uses: risclog-solution/gha_workflow_templates/.github/workflows/sonarqube.yml@master
    secrets:
      SONARQUBETOKEN: ${{ secrets.SONARQUBETOKEN }}

  publish-test-results:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/publish_test_results.yml@master

  check-release:
    needs: [test, coverage, pre-commit]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: risclog-solution/gha_workflow_templates/.github/workflows/check_release.yml@master

  release:
    needs: check-release
    if: needs.check-release.outputs.result == '1'
    uses: risclog-solution/gha_workflow_templates/.github/workflows/release.yml@master
    with:
      package_name: risclog.sqlalchemy
    secrets:
      PYPIRC: ${{ secrets.PYPIRC }}

  cleanup:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/cleanup.yml@master
